teamvolta/volta-system

- DiscoveryServer/addressStore.js
- DiscoveryServer/addressStoreModels.js
- DiscoveryServer/config.js
- DiscoveryServer/server.js
> Debug discovery#106

- AccountingServer/transactions.js
- spinupConfig.js
- spinupNodes.js
- spinupNodes.sh
> Add spinup#108

- package.json
- spinupConfig.js
- spinupNodes.js
- spinupNodes.sh
> Integrated DistMan

- AccountingServer/streaming.js
> Changed to accept subscription object

- DiscoveryServer/server.js
- SystemServer/config.js
- SystemServer/server.js
- utils/discoveryClient.js
> Integrate discovery#117

- package.json
> Updated DistMan

- AccountingServer/config.js
- AccountingServer/server.js
> Integrate accounting discovery#126

- SystemServer/consumerManager.js
- SystemServer/market/market.js
> Added transactions for producers

- AlternativeBrokerServer/broker.js
- AlternativeBrokerServer/server.js
- utils/discoveryClient.js
> Discover system#136

- SystemServer/market/receiptsModel.js
- spinupConfig.js
> Integrated with Accounting

- AccountingServer/streaming.js
- AlternativeBrokerServer/broker.js
Fix 2 bugs. Bound streaming service addSubscription to this. Fixed distribution algo in Broker.
> Fixed bugs

- SystemServer/aggregations.js
- SystemServer/market/auctionModel.js
- SystemServer/market/market.js
- SystemServer/market/pricingModels/verticalDemandAndStepwiseSupply.js
- SystemServer/server.js
- spinupConfig.js
- utils/aggregator.js
> Aggregation#154

- SystemServer/aggregations.js
- SystemServer/market/market.js
- SystemServer/server.js
Added aggregations. Close #156
> Added some aggregations

- SystemServer/public/app/dashboard/dashboard.controller.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/dashboard/dashboardBoxes.directives.js
- SystemServer/public/app/dashboard/dashboardTiles.directives.js
- SystemServer/public/app/dashboard/statBox.jade
- SystemServer/public/app/templates.jade
- SystemServer/public/index.jade
> Tile directives#162

- AccountingServer/config.js
- SystemServer/market/market.js
- spinupConfig.js
Added circle directives and created templates
> Added circle directives

- SystemServer/aggregations.js
- SystemServer/consumerManager.js
- SystemServer/producerManager.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/dashboard/dashboardTiles.directives.js
- SystemServer/public/app/dashboard/quickButton.jade
- SystemServer/public/app/services/AggregationService.js
- SystemServer/public/index.jade
- SystemServer/server.js
- utils/aggregator.js
> Implemented Tiles

- spinupConfig.js
- utils/circularBuffer.js
> Circular buffer#169

- SystemServer/aggregations.js
- test/consumerManager.test.js
- test/producerManager.test.js
- utils/aggregator.js
- utils/circularBuffer.js
> Integrate buffer#171

- SystemServer/market/market.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/dashboard/dashboardBoxes.directives.js
- SystemServer/public/app/dashboard/statBox.jade
- SystemServer/public/app/services/AggregationService.js
- SystemServer/public/app/utils/circularBuffer.js
- SystemServer/public/js/custom.js
- utils/circularBuffer.js
> Build stat boxes#174

- AlternativeBrokerServer/broker.js
- AlternativeBrokerServer/server.js
- SystemServer/aggregations.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/dashboard/dashboardBoxes.directives.js
- SystemServer/public/app/services/TransactionsService.js
- SystemServer/server.js
> Broker data nsp#180

- SystemServer/public/app/app.js
- SystemServer/public/app/dashboard/dashboard.controller.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/dashboard/dashboardBoxes.directives.js
- SystemServer/public/app/dashboard/statBox.jade
- SystemServer/public/app/network/network.controller.js
- SystemServer/public/app/network/network.directives.js
- SystemServer/public/app/network/network.jade
- SystemServer/public/app/network/networkGraph.jade
- SystemServer/public/app/services/AggregationService.js
- SystemServer/public/app/services/TransactionsService.js
- SystemServer/public/app/templates.jade
- SystemServer/public/index.jade
> Build network view#182

- AlternativeBrokerServer/broker.js
- AlternativeBrokerServer/server.js
- SystemServer/public/app/app.js
- SystemServer/public/app/dashboard/dashboard.controller.js
- SystemServer/public/app/dashboard/dashboard.jade
- SystemServer/public/app/services/TransactionsService.js
- SystemServer/public/app/templates.jade
- SystemServer/public/app/transactions/transaction.jade
- SystemServer/public/app/transactions/transactions.controller.js
- SystemServer/public/app/transactions/transactions.directives.js
- SystemServer/public/app/transactions/transactions.jade
- SystemServer/public/index.jade
> Build transactions#190

- SystemServer/public/app/dashboard/dashboard.controller.js
- SystemServer/public/js/custom.js
> Integrated Grid Load
